name: CI

on:
    push:
        branches: ["**"]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: uv sync

            - name: Comprobar errores en el código
              run: uv run ruff check .

            - name: Formatear el código
              run: uv run ruff format . --check

            - name: Verificar tipos estáticos
              run: uv run mypy .

            - name: Ejecutar tests unitarios
              run: uv run pytest ./core/tests/unit

            - name: Ejecutar tests de integración
              run: uv run pytest ./core/tests/integration

            - name: Ejecutar tests de BDD
              run: uv run pytest ./core/tests/behaviour
